---

- name: converge
  hosts: all

  pre_tasks:

    - name: update package cache
      ansible.builtin.import_tasks: ../tasks/package-cache.yml

  tasks:

    - name: include role idiv_biodiversity.nslcd
      ansible.builtin.include_role:
        name: idiv_biodiversity.nslcd

  vars:
    nsswitch_passwd: [files, ldap]
    nsswitch_group: [files, ldap]
    nsswitch_shadow: [files, ldap]

...
