---

dependency:
  name: galaxy

driver:
  name: docker

platforms:

  - name: archlinux
    image: ghcr.io/idiv-biodiversity/ansible-molecule-archlinux:latest
    command: /usr/lib/systemd/systemd
    pre_build_image: yes
    privileged: yes
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    groups:
      - nosudo

provisioner:
  name: ansible
  inventory:
    group_vars:
      nosudo:
        ansible_become_method: su

verifier:
  name: ansible

...
