---

- name: verify
  hosts: all
  tasks:

    - name: check package installation
      ansible.builtin.package:
        name: nss-pam-ldapd
        state: present
      check_mode: yes
      register: __nslcd_installed

    - name: debug package installation
      ansible.builtin.debug:
        var: __nslcd_installed

    - name: assert on package installation
      ansible.builtin.assert:
        that:
          - not __nslcd_installed.failed
          - not __nslcd_installed.changed
          - __nslcd_installed.msg == 'package(s) already installed'
        success_msg: 'package is installed'

    - name: check service
      ansible.builtin.service:
        name: nslcd
        enabled: yes
        state: started
      check_mode: yes
      register: __nslcd_service

    - name: debug service
      ansible.builtin.debug:
        var: __nslcd_service

    - name: assert on service
      ansible.builtin.assert:
        that:
          - not __nslcd_service.failed
          - not __nslcd_service.changed
          - __nslcd_service.state == 'started'
          - __nslcd_service.enabled
        success_msg: 'service is both enabled and started'

...
